---
language: node_js
node_js:
  - stable
cache:
  directories:
    - bower_components
    - node_modules
sudo: false

install:
  - npm prune
  - npm update
  - npm install

script: if [ "${TRAVIS_BRANCH}" = "${DEPLOY_BRANCH}" ] && [ ! -z "${DEPLOY_BRANCH}" ]; then npm run production; else npm run test; fi

after_success:
  - openssl aes-256-cbc -K $encrypted_aff3ecdf4eb3_key -iv $encrypted_aff3ecdf4eb3_iv -in .deploy_key.enc -out .deploy_key -d
  - eval "$(ssh-agent)"
  - chmod 600 .deploy_key
  - ssh-add .deploy_key
  - if [ "${TRAVIS_BRANCH}" = "${DEPLOY_BRANCH}" ] && [ ! -z "${DEPLOY_BRANCH}" ]; then npm run deploy; fi
